config:
  namespace: dibidabidab
  hpp_incl:
    - dibidabidab.hpp
    - nothing.hpp
    - compiletime.hpp
  cpp_incl:
    - cpp_only.hpp
    - hpp_no_include.hpp
  fwd_decl:
    - typ1
    - typ2
    - typ3

A:
  _flags:
    - json_with_keys

  b: [B, NULL]
  i: [int, 0]
  s: [string, Hello world!]
  f: float
  bol: [bool, false]


  _cpp_only:
    notForLua: [int, 0]

  _methods:
    - int simpleFunction();

  _hash:
    [b, i]

B:
  i: int