config:
  namespace: dibidabidab

A:
  _options:
    - json_with_keys

  b: [B, NULL]
  i: [int, 0]
  s: [string, Hello world!]
  f: float
  bol: [bool, false]


  _cpp_only:
    notForLua: [int, 0]

  _methods:
    - int simpleFunction();

  _hash:
    [b, i]

B:
  i: int